const noDataSearch = {
  data: {
    page: 1,
    total_results: 266,
    total_pages: 14,
    results: [{
      original_name: 'Days of Our Lives', genre_ids: [18, 10766], name: 'Days of Our Lives', popularity: 23.287, origin_country: ['US'], vote_count: 47, first_air_date: '1965-11-08', backdrop_path: '/e7MSbwYRVqd4rZQQWcNuJvOSHLC.jpg', original_language: 'en', id: 881, vote_average: 6, overview: 'The Horton and Brady broods endure the romantic trials of life in Salem, a Midwestern hamlet filled with evil geniuses, star-crossed lovers and a rich family history.', poster_path: '/7Zm7epVFEovMEVLpM6FvrjhaNXn.jpg',
    }, {
      original_name: 'Days of Delight', id: 28366, name: 'Days of Delight', popularity: 1.4, vote_count: 0, vote_average: 0, first_air_date: '1999-10-11', poster_path: null, genre_ids: [], original_language: 'en', backdrop_path: null, overview: '', origin_country: [],
    }, {
      original_name: 'Days of Hope', genre_ids: [18], name: 'Days of Hope', popularity: 1.248, origin_country: ['GB'], vote_count: 2, first_air_date: '1975-09-11', backdrop_path: null, original_language: 'en', id: 13850, vote_average: 7.5, overview: 'Days of Hope is a BBC television drama serial produced in 1975. The series dealt with the lives of a working-class family from the turmoils of the First World War in 1916 to the General Strike in 1926. It was written by Jim Allen, produced by Tony Garnett and directed by Ken Loach.', poster_path: null,
    }, {
      original_name: 'The Last Days of Pompeii', genre_ids: [18], name: 'The Last Days of Pompeii', popularity: 1.688, origin_country: ['US'], vote_count: 5, first_air_date: '1984-05-06', backdrop_path: null, original_language: 'en', id: 20755, vote_average: 7.4, overview: "This seven-hour British-Italian adaptation of Edward Bulwer-Lytton's 1834 epic, set against the eruption of Mount Vesuvius in 79 A.D. and previously filmed in 1935, and in 1960 was a vehicle for muscleman Steve Reeves, was trashed by the critics as the campiest of sword and sandal sagas to emerge in years. This despite its reported $19-million price tag, the nobility of its cast that includes Laurence Olivier, Siobhan McKenna and Anthony Quayle, and its rather unspectacular special effects. The central figures are Nicholas Clay as Glaucus, the noble Athenian; Olivia Hussey as the high-born Ione, his love, who is seduced by the Egyptian, Arbaces (Franco Nero), a religious fanatic; Duncan Regehr as Lydon, the champion gladiator; and Linda Purl as the blind slave Nydia, who is torn between Glaucus and Lydon.", poster_path: '/fOt6PRXzHR9NMvf6Hag7Sg4qbAx.jpg',
    }, {
      original_name: 'Days of Revolt', id: 66019, name: 'Days of Revolt', popularity: 0.6, vote_count: 0, vote_average: 0, first_air_date: '2015-08-03', poster_path: null, genre_ids: [99, 10767, 10768], original_language: 'en', backdrop_path: null, overview: 'A platform to dissidents and rebels, both within the United States and abroad, who offer critiques of power not heard within mainstream society or permitted by the corporate press. Host Chris Hedges and his guests lay bare the mechanisms that uphold systems of power, including the role of the military and the internal security apparatus, as well as the elaborate forms of propaganda and corporate-controlled media.', origin_country: ['US'],
    }, {
      original_name: 'The Last Days Of...', id: 88314, name: 'The Last Days Of...', popularity: 0.6, vote_count: 0, vote_average: 0, first_air_date: '2015-09-04', poster_path: null, genre_ids: [99], original_language: 'en', backdrop_path: null, overview: 'The lives and deaths of the heroes and villains who have shaped our world. History is peppered with men and women who changed the world, only to become more controversial in death than they were in life. ʻThe Last Days of...ʼ examines six giants of history who suffered bloody and brutal deaths, retelling their stories, which are packed with unexpected twists and turns. Each episode features a panel of writers, thinkers and historians who set about exploring the downfall and legacy of these characters. This is history as it should be - compelling, dramatic and highly contested. It makes us question everything we thought we knew about the lives and deaths of the heroes and villains who have shaped our world.', origin_country: [],
    }, {
      original_name: '30 Days of Night: Blood Trails', genre_ids: [], name: '30 Days of Night: Blood Trails', popularity: 1.219, origin_country: ['US'], vote_count: 7, first_air_date: '2007-09-13', backdrop_path: null, original_language: 'en', id: 14633, vote_average: 5.1, overview: '30 Days of Night: Blood Trails is a 7-part miniseries that was released on FEARnet.com and FEARnet On Demand that acts as a prequel to the films 30 Days of Night and 30 Days of Night: Dark Days. Set two days before the events in the first film, the series focuses on George, a young addict who makes a living seeking covert information for Judith, the weary but wise New Orleans, Louisiana vampire hunter. It is based on a subplot of the original comic that was left out of the movie.', poster_path: null,
    }, {
      original_name: '30 Days of Night: Dust to Dust', genre_ids: [10765], name: '30 Days of Night: Dust to Dust', popularity: 1.707, origin_country: ['US'], vote_count: 2, first_air_date: '2008-07-17', backdrop_path: null, original_language: 'en', id: 21139, vote_average: 5.5, overview: 'Detective Nick Maguire learns that his sister Sara, a nurse at the local penitentiary, disappeared during a mysterious prison break in which George escaped. While scouring the gritty streets of New Orleans, Nick finds George and learns that there was more to the prison break than anyone thought. Now, in order to save his sister, Nick will have to learn to trust George.', poster_path: null,
    }, {
      original_name: '7 Days of Sex', genre_ids: [10764], name: '7 Days of Sex', popularity: 0.6, origin_country: ['US'], vote_count: 0, first_air_date: '2012-04-26', backdrop_path: null, original_language: 'en', id: 42754, vote_average: 0, overview: ' 7 Days of Sex is a reality TV series exploring the benefits of regular sex. Each week, two struggling couples takes on the challenge to have sex each and every day and document the entire experience. If the week works, they renew their vows. And if it doesn’t, they say their farewells.', poster_path: null,
    }, {
      original_name: 'Six Days of Justice', genre_ids: [], name: 'Six Days of Justice', popularity: 0.6, origin_country: ['GB'], vote_count: 0, first_air_date: '1972-04-10', backdrop_path: null, original_language: 'en', id: 25344, vote_average: 0, overview: 'Six Days of Justice is a British television drama anthology series of single plays created by Thames Television and shown on ITV from 1972 to 1975, over four seasons of six episodes apiece.', poster_path: '/wX6QMiurN4Jyg1VzDyMUmez7qlV.jpg',
    }, {
      original_name: 'The Days of Vengeance', id: 27948, name: 'The Days of Vengeance', popularity: 0.6, vote_count: 0, vote_average: 0, first_air_date: '1960-06-08', poster_path: null, genre_ids: [], original_language: 'en', backdrop_path: null, overview: '', origin_country: ['GB'],
    }, {
      original_name: 'The Last Days of Lehman Brothers', genre_ids: [99, 18], name: 'The Last Days of Lehman Brothers', popularity: 1.126, origin_country: ['GB'], vote_count: 0, first_air_date: '2009-09-09', backdrop_path: null, original_language: 'en', id: 30935, vote_average: 0, overview: "The Last Days of Lehman Brothers is a British television film, first broadcast on BBC Two and BBC HD on Wednesday 9 September 2009. Filmed in London, it was written by Craig Warner and directed by Michael Samuels. It was shown as part of the BBC's \"Aftershock\" season, a selection of programmes marking the first anniversary of the collapse of the American investment bank Lehman Brothers. It featured James Cromwell, Ben Daniels, Corey Johnson, Michael Landes and James Bolam.", poster_path: null,
    }, {
      original_name: 'The Days and Nights of Molly Dodd', genre_ids: [35, 18], name: 'The Days and Nights of Molly Dodd', popularity: 5.339, origin_country: ['US'], vote_count: 0, first_air_date: '1987-05-21', backdrop_path: null, original_language: 'en', id: 524, vote_average: 0, overview: 'The Days and Nights of Molly Dodd is an American comedy-drama series that aired on NBC from 1987 to 1988, and on Lifetime from 1988 to 1991. It was created by Jay Tarses and stars Blair Brown in the title role.', poster_path: null,
    }, {
      original_name: 'The Last Days of Kennedy and King', id: 47205, name: 'The Last Days of Kennedy and King', popularity: 0.6, vote_count: 0, vote_average: 0, first_air_date: '', poster_path: null, genre_ids: [], original_language: 'en', backdrop_path: null, overview: '', origin_country: [],
    }, {
      original_name: 'The Good Old Days of Radio', id: 51379, name: 'The Good Old Days of Radio', popularity: 0.6, vote_count: 0, vote_average: 0, first_air_date: '', poster_path: null, genre_ids: [], original_language: 'en', backdrop_path: null, overview: '', origin_country: [],
    }, {
      original_name: 'The Day of Days', id: 56018, name: 'The Day of Days', popularity: 0.6, origin_country: ['HK'], original_language: 'en', vote_count: 0, backdrop_path: null, genre_ids: [], vote_average: 0, overview: 'The Day of Days is a 2013 Hong Kong television period-drama serial produced by TVB under producer Leung Choi-yuen. The serial premiered on Monday, 21 January 2013 on Jade and HD Jade, and is slated to run for 20 episodes.', poster_path: null,
    }, {
      original_name: 'Revelation: The End of Days', id: 61809, name: 'Revelation: The End of Days', popularity: 0.84, vote_count: 1, vote_average: 5, first_air_date: '2014-12-29', poster_path: null, genre_ids: [18], original_language: 'en', backdrop_path: null, overview: 'Almost 2,000 years ago, the final book of the Bible, Revelation, predicted that Christ would return but only after a period of chaos and torment inflicted on the world to test the faith of mankind. REVELATION: THE END OF DAYS is a gripping, dramatic interpretation of how the ancient prophecies of The Book of Revelation could unfold in our modern world. The two-night, four-hour event brings to life six fictional characters’ firsthand accounts of the “End of Days” events.\n\nREVELATION: THE END OF DAYS merges drama with re-purposed real news archive to thrust a group of fictional characters into an imagining of the Apocalypse. The program follows the dramatic stories of a TV reporter, a police officer, a doctor, a scientist and a college professor as they deal with chaos, war, earthquakes and a deadly pandemic.', origin_country: [],
    }, {
      original_name: 'Czas honoru', genre_ids: [99, 18, 10759], name: 'Days of Honor', popularity: 5.744, origin_country: ['PL'], vote_count: 1, first_air_date: '2008-09-07', backdrop_path: null, original_language: 'pl', id: 42381, vote_average: 7, overview: 'Days of honor is a Polish World War II television drama series, broadcast on TVP2 since September 7, 2008.', poster_path: null,
    }, {
      original_name: 'D-Day: The Longest of Days', genre_ids: [], name: 'D-Day: The Longest of Days', popularity: 0.6, origin_country: [], vote_count: 0, first_air_date: '2019-01-01', backdrop_path: null, original_language: 'en', id: 97176, vote_average: 0, overview: "Witness the events leading up to the Normandy Invasion, famously known as 'D-Day'. Cameramen took to the battlefield to document the genuine experience of war.", poster_path: null,
    }, {
      original_name: 'Happy Days', genre_ids: [35], name: 'Happy Days', popularity: 27.315, origin_country: ['US'], vote_count: 100, first_air_date: '1974-01-15', backdrop_path: '/iy1E0OjT6k3cPnuC7r6CjJifFcA.jpg', original_language: 'en', id: 3845, vote_average: 7.6, overview: "A nostalgic comedy set in 1950s Milwaukee centered on the squeaky-clean Cunningham family and their relationship with Fonzie, a motorcycle-riding Casanova who became a pop-culture phenomenon during the show's heyday in the 1970s.", poster_path: '/oTjJPlENoZSuO2cblfUISM6jnGN.jpg',
    }],
  },
  status: 200,
  statusText: '',
  headers: { 'cache-control': 'public, max-age=120', 'content-type': 'application/json;charset=utf-8' },
  config: {
    url: 'https://api.themoviedb.org/3/search/tv?', method: 'get', params: { api_key: process.env.GATSBY_API_KEY, query: 'days of' }, headers: { Accept: 'application/json, text/plain, */*' }, transformRequest: [null], transformResponse: [null], timeout: 0, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1,
  },
  request: {},
};

export default noDataSearch;
